# Major
set(A2XTECH_VERSION_1 1)
# Minor
set(A2XTECH_VERSION_2 3)
# Revision
set(A2XTECH_VERSION_3 1)
# Patch
set(A2XTECH_VERSION_4 0)
# Type of version: "-alpha","-beta","-dev", or "" aka "release"
set(A2XTECH_VERSION_REL "")

add_definitions(-DA2XTECH_VERSION_1=${A2XTECH_VERSION_1})
add_definitions(-DA2XTECH_VERSION_2=${A2XTECH_VERSION_2})
add_definitions(-DA2XTECH_VERSION_3=${A2XTECH_VERSION_3})
add_definitions(-DA2XTECH_VERSION_4=${A2XTECH_VERSION_4})
add_definitions(-DA2XTECH_VERSION_REL=${A2XTECH_VERSION_REL})

set(A2XTECH_VERSION_STRING "${A2XTECH_VERSION_1}.${A2XTECH_VERSION_2}")

if(NOT ${A2XTECH_VERSION_3} EQUAL 0 OR NOT ${A2XTECH_VERSION_4} EQUAL 0)
    string(CONCAT A2XTECH_VERSION_STRING "${A2XTECH_VERSION_STRING}" ".${A2XTECH_VERSION_3}")
endif()

if(NOT ${A2XTECH_VERSION_4} EQUAL 0)
    string(CONCAT A2XTECH_VERSION_STRING "${A2XTECH_VERSION_STRING}" ".${A2XTECH_VERSION_4}")
endif()

if(NOT "${A2XTECH_VERSION_REL}" STREQUAL "")
    string(CONCAT A2XTECH_VERSION_STRING "${A2XTECH_VERSION_STRING}" "${A2XTECH_VERSION_REL}")
endif()

message("== A2xTech version ${A2XTECH_VERSION_STRING} ==")
