#include "globals.h"

FrmMain frmMain;
GFX gfx;

bool GameIsActive = false;

int numSavedEvents = 0;
RangeArr<std::string, 1, MaxSavedEvents> SavedEvents;
RangeArr<bool, 1, 4> BlockSwitch;
RangeArr<bool, 2, 7> PowerUpUnlock;
long myBackBuffer = 0;
long myBufferBMP = 0;
int AllCharBlock = 0;
bool StartMenu = false;
int BlockFlash = 0;
bool ScrollRelease = false;
bool TakeScreen = false;
std::string LB;
std::string EoT;
RangeArr<ConKeyboard, 1, 2> conKeyboard;
RangeArr<ConJoystick, 1, 2> conJoystick;
RangeArr<int, 1, 2> useJoystick;

int ScreenShake = 0;
std::string Checkpoint;
bool MagicHand = false;
RangeArr<Player, 1, 2> testPlayer;
bool ClearBuffer = false;
int numLocked = 0;
bool resChanged = false;
int inputKey = 0;
bool getNewKeyboard = false;
bool getNewJoystick = false;
int lastJoyButton = 0;
bool GamePaused = false;
bool MessageText = false;
int NumSelectWorld  = 0;
RangeArr<SelectWorld, 1, 100> selectWorld;
bool ShowFPS = false;
double PrintFPS = 0.0;
RangeArr<vScreen, 0, 2> vscreen;
int ScreenType = 0;
int DScreenType = 0;
bool LevelEditor = false;
bool WorldEditor = false;
RangeArr<Location, 1, 2> PlayerStart;
RangeArr<bool, 0, 20> blockCharacter;
RangeArr<int, 0, maxPlayers> OwedMount;
RangeArr<int, 0, maxPlayers> OwedMountType;
RangeArr<float, 0, maxSections> AutoX;
RangeArr<float, 0, maxSections> AutoY;
int numStars = 0;
RangeArr<Water, 0, maxWater> water;
int numWater = 0;
RangeArr<Star, 1, 1000> star;
std::string GoToLevel;
std::string StartLevel;
bool NoMap = false;
bool RestartLevel = false;
float LevelChop[maxSections + 1];
RangeArr<int, -FLBlocks, FLBlocks> FirstBlock;
RangeArr<int, -FLBlocks, FLBlocks> LastBlock;
int MidBackground = 0;
int LastBackground = 0;
int iBlocks;
RangeArr<int, 0, maxBlocks> iBlock;
int numTiles;
int numScenes;
RangeArr<std::string, 0, maxSections> CustomMusic;
RangeArr<Location, 0, maxSections> level;
RangeArr<bool, 0, maxSections> LevelWrap;
RangeArr<bool, 0, maxSections> OffScreenExit;
RangeArr<int, 0, maxSections> bgMusic;
RangeArr<int, 0, maxSections> bgMusicREAL;
RangeArr<int, 0, maxSections> Background2REAL;
RangeArr<Location, 0, maxSections> LevelREAL;
int curMusic;
RangeArr<long, 0, maxSections> bgColor;
RangeArr<int, 0, maxSections> Background2;
RangeArr<WorldPath, 1, maxWorldPaths> worldPath;
int numWorldPaths;
int numWarps;
RangeArr<Warp, 1, maxWarps> warp;
RangeArr<Tile, 1, maxTiles> tile;
RangeArr<Scene, 1, maxScenes> scene;
RangeArr<CreditLine, 1, 200> credit;
int numCredits;
int numBlock;
int numBackground;
int numNPCs;
int numEffects;
int numPlayers;
int numWorldLevels;
RangeArr<WorldMusic, 1, maxWorldMusic> worldMusic;
int numWorldMusic;
RangeArr<WorldLevel, 1, maxWorldLevels> worldLevel;
RangeArr<Background, 1, maxBackgrounds> background;
RangeArr<Effect, 1, maxEffects> effect;
RangeArr<NPC, 1, maxNPCs> npc;
RangeArr<Block, 0, maxBlocks> block;
RangeArr<Player, 0, maxPlayers> player;
RangeArr<int, 0, maxPlayerFrames> MarioFrameX;
RangeArr<int, 0, maxPlayerFrames> MarioFrameY;
RangeArr<int, 0, maxPlayerFrames> LuigiFrameX;
RangeArr<int, 0, maxPlayerFrames> LuigiFrameY;
RangeArr<int, 0, maxPlayerFrames> PeachFrameX;
RangeArr<int, 0, maxPlayerFrames> PeachFrameY;
RangeArr<int, 0, maxPlayerFrames> ToadFrameX;
RangeArr<int, 0, maxPlayerFrames> ToadFrameY;
RangeArr<int, 0, maxPlayerFrames> LinkFrameX;
RangeArr<int, 0, maxPlayerFrames> LinkFrameY;
RangeArr<bool, 0, maxBackgroundType> BackgroundFence;
RangeArr<int, 0, maxNPCType> NPCFrameOffsetX;
RangeArr<int, 0, maxNPCType> NPCFrameOffsetY;
RangeArr<int, 0, maxNPCType> NPCWidth;
RangeArr<int, 0, maxNPCType> NPCHeight;
RangeArr<int, 0, maxNPCType> NPCWidthGFX;
RangeArr<int, 0, maxNPCType> NPCHeightGFX;
RangeArr<float, 0, maxNPCType> NPCSpeedvar;
RangeArr<bool, 0, maxNPCType> NPCIsAShell;
RangeArr<bool, 0, maxNPCType> NPCIsABlock;
RangeArr<bool, 0, maxNPCType> NPCIsAHit1Block;
RangeArr<bool, 0, maxNPCType> NPCIsABonus;
RangeArr<bool, 0, maxNPCType> NPCIsACoin;
RangeArr<bool, 0, maxNPCType> NPCIsAVine;
RangeArr<bool, 0, maxNPCType> NPCIsAnExit;
RangeArr<bool, 0, maxNPCType> NPCIsAParaTroopa;
RangeArr<bool, 0, maxNPCType> NPCIsCheep;
RangeArr<bool, 0, maxNPCType> NPCJumpHurt;
RangeArr<bool, 0, maxNPCType> NPCNoClipping;
RangeArr<int, 0, maxNPCType> NPCScore;
RangeArr<bool, 0, maxNPCType> NPCCanWalkOn;
RangeArr<bool, 0, maxNPCType> NPCGrabFromTop;
RangeArr<bool, 0, maxNPCType> NPCTurnsAtCliffs;
RangeArr<bool, 0, maxNPCType> NPCWontHurt;
RangeArr<bool, 0, maxNPCType> NPCMovesPlayer;
RangeArr<bool, 0, maxNPCType> NPCStandsOnPlayer;
RangeArr<bool, 0, maxNPCType> NPCIsGrabbable;
RangeArr<bool, 0, maxNPCType> NPCIsBoot;
RangeArr<bool, 0, maxNPCType> NPCIsYoshi;
RangeArr<bool, 0, maxNPCType> NPCIsToad;
RangeArr<bool, 0, maxNPCType> NPCNoYoshi;
RangeArr<bool, 0, maxNPCType> NPCForeground;
RangeArr<bool, 0, maxNPCType> NPCIsABot;
RangeArr<bool, 0, maxNPCType> NPCDefaultMovement;
RangeArr<bool, 0, maxNPCType> NPCIsVeggie;
RangeArr<bool, 0, maxNPCType> NPCNoFireBall;
RangeArr<bool, 0, maxNPCType> NPCNoIceBall;
RangeArr<bool, 0, maxNPCType> NPCNoGravity;

RangeArr<int, 0, maxNPCType> NPCFrame;
RangeArr<int, 0, maxNPCType> NPCFrameSpeed;
RangeArr<int, 0, maxNPCType> NPCFrameStyle;

NPCDefaults npcDefaults;

RangeArr<bool, 0, maxBlockType> BlockIsSizable;
RangeArr<int, 0, maxBlockType> BlockSlope;
RangeArr<int, 0, maxBlockType> BlockSlope2;
RangeArr<double, 0, maxPlayers> vScreenX;
RangeArr<double, 0, maxPlayers> vScreenY;

RangeArr<double, 0, maxPlayers> qScreenX;
RangeArr<double, 0, maxPlayers> qScreenY;
bool qScreen = false;

RangeArr<int, 0, maxBlockType> BlockWidth;
RangeArr<int, 0, maxBlockType> BlockHeight;
RangeArr<int, 0, maxBlockType> BonusWidth;
RangeArr<int, 0, maxBlockType> BonusHeight;
RangeArr<int, 0, maxBlockType> EffectWidth;
RangeArr<int, 0, maxBlockType> EffectHeight;

EffectDefaults effectDefaults;
RangeArr<int, 1, maxSceneType> SceneWidth;
RangeArr<int, 1, maxSceneType> SceneHeight;
RangeArr<bool, 1, maxBackgroundType> BackgroundHasNoMask;
RangeArr<bool, 0, maxBackgroundType> Foreground;
RangeArr<int, 1, maxBackgroundType> BackgroundWidth;
RangeArr<int, 1, maxBackgroundType> BackgroundHeight;
RangeArr<int, 1, maxBackgroundType> BackgroundFrame;
RangeArr<int, 1, maxBackgroundType> BackgroundFrameCount;
RangeArr<int, 1, maxBlockType> BlockFrame;
RangeArr<int, 1, maxBlockType> BlockFrame2;
RangeArr<int, 1, 1000> sBlockArray;
int sBlockNum = 0;
RangeArr<int, 1, maxSceneType> SceneFrame;
RangeArr<int, 1, maxSceneType> SceneFrame2;
RangeArr<int, 1, maxTileType> TileWidth;
RangeArr<int, 1, maxTileType> TileHeight;
RangeArr<int, 1, maxTileType> TileFrame;
RangeArr<int, 1, maxTileType> TileFrame2;
RangeArr<int, 1, 100> LevelFrame;
RangeArr<int, 1, 100> LevelFrame2;
RangeArr<bool, 1, maxBlockType> BlockHasNoMask;
RangeArr<bool, 1, 100> LevelHasNoMask;
RangeArr<bool, 0, maxBlockType> BlockOnlyHitspot1;
RangeArr<bool, 0, maxBlockType> BlockKills;
RangeArr<bool, 0, maxBlockType> BlockKills2;
RangeArr<bool, 0, maxBlockType> BlockHurts;
RangeArr<bool, 0, maxBlockType> BlockPSwitch;
RangeArr<bool, 0, maxBlockType> BlockNoClipping;
RangeArr<int, 1, 10> CoinFrame;
RangeArr<int, 1, 10> CoinFrame2;
EditorCursor editorCursor;

RangeArr<int, 1, numSounds> Sound;
RangeArr<int, 1, numSounds> SoundPause;
bool EndLevel = false;
int LevelMacro;
int LevelMacroCounter;
int numJoysticks;
std::string FileName;
int Coins;
float Lives;
bool EndIntro;
bool ExitMenu;
bool LevelSelect;
RangeArr<WorldPlayer, 0, 1> worldPlayer;
int LevelBeatCode;
int curWorldLevel;
int curWorldMusic;
RangeArr<bool, 0, maxSections> NoTurnBack;
RangeArr<bool, 0, maxSections> UnderWater;
bool TestLevel;
std::string FullFileName;
std::string FileNamePath;
bool GameMenu;
std::string WorldName;
int selWorld;
int selSave;
int PSwitchTime;
int PSwitchStop;
int PSwitchPlayer;
RangeArr<int, 1, 3> SaveSlot;
RangeArr<int, 1, 3> SaveStars;
int BeltDirection;
bool BeatTheGame;
int cycleCount;
double fpsTime;
double fpsCount;
bool FrameSkip;
double GoalTime;
double overTime;
int worldCurs;
int minShow;
int maxShow;

RangeArr<Layer, 0, 100> layer;
RangeArr<Events, 0, 100> events;
int ReturnWarp;
int StartWarp;
Physics physics;
int MenuCursor;
int MenuMode;
bool MenuCursorCanMove;
bool MenuCursorCanMove2;
bool NextFrame;
int StopHit;
bool MouseRelease;
bool TestFullscreen;
bool keyDownAlt;
bool keyDownEnter;
bool BlocksSorted;
int SingleCoop;
std::string CheatString;
bool GameOutro;
float CreditChop;
int EndCredits;
int curStars;
int maxStars;
bool ShadowMode;
bool MultiHop;
bool SuperSpeed;
bool WalkAnywhere;
bool FlyForever;
bool FreezeNPCs;
bool CaptainN;
bool FlameThrower;
bool CoinMode;
bool WorldUnlock;
bool MaxFPS;
bool GodMode;
bool GrabAll;
bool Cheater;
RangeArr<std::string, 1, 5> WorldCredits;
int Score;
RangeArr<int, 1, 13> Points;
int oldJumpJoy;
int MaxWorldStars;
bool Debugger;
RangeArr<Player, 0, 10> SavedChar;

int LoadCoins;
float LoadCoinsT;

RangeArr<bool, 1, maxBlockType> GFXBlockCustom;
RangeArr<long, 1, maxBlockType> GFXBlock;
RangeArr<long, 1, maxBlockType> GFXBlockMask;
RangeArr<StdPicture, 1, maxBlockType> GFXBlockBMP;
RangeArr<StdPicture, 1, maxBlockType> GFXBlockMaskBMP;
RangeArr<bool, 1, numBackground2> GFXBackground2Custom;
RangeArr<long, 1, numBackground2> GFXBackground2;
RangeArr<StdPicture, 1, numBackground2> GFXBackground2BMP;
RangeArr<int, 1, numBackground2> GFXBackground2Height;
RangeArr<int, 1, numBackground2> GFXBackground2Width;
RangeArr<bool, 1, maxNPCType> GFXNPCCustom;
RangeArr<long, 1, maxNPCType> GFXNPC;
RangeArr<long, 1, maxNPCType> GFXNPCMask;
RangeArr<StdPicture, 1, maxNPCType> GFXNPCBMP;
RangeArr<StdPicture, 1, maxNPCType> GFXNPCMaskBMP;
RangeArr<int, 1, maxNPCType> GFXNPCHeight;
RangeArr<int, 1, maxNPCType> GFXNPCWidth;
RangeArr<bool, 1, maxEffectType> GFXEffectCustom;
RangeArr<long, 1, maxEffectType> GFXEffect;
RangeArr<long, 1, maxEffectType> GFXEffectMask;
RangeArr<StdPicture, 1, maxEffectType> GFXEffectBMP;
RangeArr<StdPicture, 1, maxEffectType> GFXEffectMaskBMP;
RangeArr<int, 1, maxEffectType> GFXEffectHeight;
RangeArr<int, 1, maxEffectType> GFXEffectWidth;
RangeArr<bool, 1, maxBackgroundType> GFXBackgroundCustom;
RangeArr<long, 1, maxBackgroundType> GFXBackground;
RangeArr<long, 1, maxBackgroundType> GFXBackgroundMask;
RangeArr<StdPicture, 1, maxBackgroundType> GFXBackgroundBMP;
RangeArr<StdPicture, 1, maxBackgroundType> GFXBackgroundMaskBMP;
RangeArr<int, 1, maxBackgroundType> GFXBackgroundHeight;
RangeArr<int, 1, maxBackgroundType> GFXBackgroundWidth;
RangeArr<bool, 1, 10> GFXMarioCustom;
RangeArr<long, 1, 10> GFXMario;
RangeArr<long, 1, 10> GFXMarioMask;
RangeArr<StdPicture, 1, 10> GFXMarioBMP;
RangeArr<StdPicture, 1, 10> GFXMarioMaskBMP;
RangeArr<int, 1, 10> GFXMarioHeight;
RangeArr<int, 1, 10> GFXMarioWidth;
RangeArr<bool, 1, 10> GFXLuigiCustom;
RangeArr<long, 1, 10> GFXLuigi;
RangeArr<long, 1, 10> GFXLuigiMask;
RangeArr<StdPicture, 1, 10> GFXLuigiBMP;
RangeArr<StdPicture, 1, 10> GFXLuigiMaskBMP;
RangeArr<int, 1, 10> GFXLuigiHeight;
RangeArr<int, 1, 10> GFXLuigiWidth;
RangeArr<bool, 1, 10> GFXPeachCustom;
RangeArr<long, 1, 10> GFXPeach;
RangeArr<long, 1, 10> GFXPeachMask;
RangeArr<StdPicture, 1, 10> GFXPeachBMP;
RangeArr<StdPicture, 1, 10> GFXPeachMaskBMP;
RangeArr<int, 1, 10> GFXPeachHeight;
RangeArr<int, 1, 10> GFXPeachWidth;
RangeArr<bool, 1, 10> GFXToadCustom;
RangeArr<long, 1, 10> GFXToad;
RangeArr<long, 1, 10> GFXToadMask;
RangeArr<StdPicture, 1, 10> GFXToadBMP;
RangeArr<StdPicture, 1, 10> GFXToadMaskBMP;
RangeArr<int, 1, 10> GFXToadHeight;
RangeArr<int, 1, 10> GFXToadWidth;

RangeArr<bool, 1, 10> GFXLinkCustom;
RangeArr<long, 1, 10> GFXLink;
RangeArr<long, 1, 10> GFXLinkMask;
RangeArr<StdPicture, 1, 10> GFXLinkBMP;
RangeArr<StdPicture, 1, 10> GFXLinkMaskBMP;
RangeArr<int, 1, 10> GFXLinkHeight;
RangeArr<int, 1, 10> GFXLinkWidth;

RangeArr<bool, 1, 10> GFXYoshiBCustom;
RangeArr<long, 1, 10> GFXYoshiB;
RangeArr<long, 1, 10> GFXYoshiBMask;
RangeArr<StdPicture, 1, 10> GFXYoshiBBMP;
RangeArr<StdPicture, 1, 10> GFXYoshiBMaskBMP;
RangeArr<bool, 1, 10> GFXYoshiTCustom;
RangeArr<long, 1, 10> GFXYoshiT;
RangeArr<long, 1, 10> GFXYoshiTMask;
RangeArr<StdPicture, 1, 10> GFXYoshiTBMP;
RangeArr<StdPicture, 1, 10> GFXYoshiTMaskBMP;
RangeArr<long, 1, maxTileType> GFXTileCustom;
RangeArr<long, 1, maxTileType> GFXTile;
RangeArr<StdPicture, 1, maxTileType> GFXTileBMP;
RangeArr<int, 1, maxTileType> GFXTileHeight;
RangeArr<int, 1, maxTileType> GFXTileWidth;
RangeArr<long, 0, maxLevelType> GFXLevelCustom;
RangeArr<long, 0, maxLevelType> GFXLevel;
RangeArr<long, 0, maxLevelType> GFXLevelMask;
RangeArr<StdPicture, 0, maxLevelType> GFXLevelBMP;
RangeArr<StdPicture, 0, maxLevelType> GFXLevelMaskBMP;
RangeArr<int, 0, maxLevelType> GFXLevelHeight;
RangeArr<int, 0, maxLevelType> GFXLevelWidth;
RangeArr<bool, 0, maxLevelType> GFXLevelBig;
RangeArr<long, 1, maxSceneType> GFXSceneCustom;
RangeArr<long, 1, maxSceneType> GFXScene;
RangeArr<long, 1, maxSceneType> GFXSceneMask;
RangeArr<StdPicture, 1, maxSceneType> GFXSceneBMP;
RangeArr<StdPicture, 1, maxSceneType> GFXSceneMaskBMP;
RangeArr<int, 1, maxSceneType> GFXSceneHeight;
RangeArr<int, 1, maxSceneType> GFXSceneWidth;
RangeArr<long, 1, maxPathType> GFXPathCustom;
RangeArr<long, 1, maxPathType> GFXPath;
RangeArr<long, 1, maxPathType> GFXPathMask;
RangeArr<StdPicture, 1, maxPathType> GFXPathBMP;
RangeArr<StdPicture, 1, maxPathType> GFXPathMaskBMP;
RangeArr<int, 1, maxPathType> GFXPathHeight;
RangeArr<int, 1, maxPathType> GFXPathWidth;

RangeArr<long, 1, numCharacters> GFXPlayerCustom;
RangeArr<long, 1, numCharacters> GFXPlayer;
RangeArr<long, 1, numCharacters> GFXPlayerMask;
RangeArr<StdPicture, 1, numCharacters> GFXPlayerBMP;
RangeArr<StdPicture, 1, numCharacters> GFXPlayerMaskBMP;
RangeArr<int, 1, numCharacters> GFXPlayerHeight;
RangeArr<int, 1, numCharacters> GFXPlayerWidth;

int PlayerCharacter;
int PlayerCharacter2;
double MenuMouseX;
double MenuMouseY;
bool MenuMouseDown;
bool MenuMouseBack;
bool MenuMouseRelease;
bool MenuMouseMove;
bool MenuMouseClick;

RangeArr<std::string, 1, 100> NewEvent;
RangeArr<int, 1, 100> newEventDelay;
int newEventNum;
bool ForcedControls;
Controls ForcedControl;
int SyncCount;
bool noUpdate;
double gameTime;
bool noSound;
double tempTime;
bool BattleMode;
int BattleWinner;
RangeArr<int, 1, maxPlayers> BattleLives;
int BattleIntro;
int BattleOutro;
std::string LevelName;

void DoEvents()
{
    frmMain.doEvents();
}

int ShowCursor(int show)
{
    return SDL_ShowCursor(show);
}
