# If platform is Emscripten
if(${CMAKE_SYSTEM_NAME} STREQUAL "Emscripten")
    set(EMSCRIPTEN 1 BOOLEAN)
    unset(WIN32)
    unset(APPLE)
endif()

# Define iOS/tvOS/visionOS/watchOS platform markers if they are missing (at some old CMake toolchains)
if(${CMAKE_SYSTEM_NAME} STREQUAL "iOS")
    if(NOT DEFINED IOS)
        set(IOS TRUE)
    endif()

    if(NOT DEFINED PLATFORM_IOS)
        set(PLATFORM_IOS TRUE)
    endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "tvOS")
    if(NOT DEFINED TVOS)
        set(TVOS TRUE)
    endif()

    if(NOT DEFINED PLATFORM_TVOS)
        set(PLATFORM_TVOS TRUE)
    endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "watchOS")
    if(NOT DEFINED WATCHOS)
        set(WATCHOS TRUE)
    endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "visionOS")
    if(NOT DEFINED VISIONOS)
        set(VISIONOS TRUE)
    endif()
elseif(APPLE AND NOT IOS AND NOT TVOS AND NOT VISIONOS AND NOT WATCHOS)
    if(NOT DEFINED MACOS)
        set(MACOS 1)
    endif()
endif()
