set(liblz4_Libs "${DEPENDENCIES_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}lz4${PGE_LIBS_DEBUG_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}")

ExternalProject_Add(
    lz4_Local
    PREFIX ${CMAKE_BINARY_DIR}/external/lz4
    DOWNLOAD_COMMAND ""
    SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}/../3rdparty/lz4/build/cmake
    CMAKE_ARGS
        "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
        "-DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}"
        "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
        "-DCMAKE_CONFIGURATION_TYPES=${CMAKE_CONFIGURATION_TYPES}"
        "-DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}"
        "-DCMAKE_POSITION_INDEPENDENT_CODE=${FREETYPE_PIC}"
        "-DCMAKE_DEBUG_POSTFIX=${PGE_LIBS_DEBUG_SUFFIX}"
        "-DDISABLE_FORCE_DEBUG_POSTFIX=ON"
        "-DLZ4_BUILD_CLI=OFF"
        "-DLZ4_BUNDLED_MODE=OFF"
        "-DBUILD_SHARED_LIBS=OFF"
        ${ANDROID_CMAKE_FLAGS}
        $<$<BOOL:APPLE>:-DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}>
        $<$<BOOL:APPLE>:-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}>
    BUILD_BYPRODUCTS
        "${liblz4_Libs}"
)

set(LZ4_INCLUDE_DIRS "${DEPENDENCIES_INSTALL_DIR}/include" CACHE "" STRING FORCE)
set(LZ4_LIBRARIES ${liblz4_Libs} CACHE "" STRING FORCE)

set(USE_EXTERNAL_LZ4 ON CACHE "" BOOLEAN FORCE)
set(MBEDISO_BUILD_EXECUTABLES OFF CACHE "" BOOLEAN FORCE)
add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/mbediso EXCLUDE_FROM_ALL)
add_dependencies(mbediso lz4_Local)

if(NOT THEXTECH_NO_SDL_BUILD)
    if(NOT USE_SYSTEM_SDL2)
        target_include_directories(mbediso PRIVATE "${DEPENDENCIES_INSTALL_DIR}/include")
        add_dependencies(mbediso AudioCodecs_Local)
    else()
        target_include_directories(mbediso PRIVATE "${SDL2_INCLUDE_DIRS}")
    endif()
endif()

if(ANDROID)
    set_target_properties(lz4 PROPERTIES POSITION_INDEPENDENT_CODE ON)
    set_target_properties(lz4_static PROPERTIES POSITION_INDEPENDENT_CODE ON)
    set_target_properties(mbediso PROPERTIES POSITION_INDEPENDENT_CODE ON)
endif()
